### ISSUE TITLE
The Copper Fill is Not Connected

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#1]
## Summary
As of 20240417 the front copper fill is not connected to a net.
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/5242f4e7-0d96-47d5-91cb-be4473e87aaf)

### Suggested Fix
It would be best to connect to the net "GND".
Then back in the PCB editor, press the "b" to repour the fill. 

### Demonstrate Fix
Show the results in another comment to this issue.

**Comment by nk25719** [comment]
<img width="954" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/776e93cb-9eaf-4024-a834-27f71d3ddf38">

I followed your suggestions and this is the result image.

**Comment by ForrestErickson** [comment]
Lee confirms the change has fixed the issue. The copper fill is connected to GND.
