### ISSUE TITLE
Place Capacitors For Better High Frequency Effectives. 

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#12]
## Three terminal regulator Circuit
Locate C4, C5, C6 and C7 near U1. The Small Value Capacitors Nearest U1
And move all of the parts near the power barrel jack.

Similar to this:
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/6a2bb1f7-ecb5-4849-a058-9a7215e54617)

## ESP32 Power Supply Filtering
Move C1 and C3 near the power and ground pins of ESP32.  Ground pin 2 on ESP32.

Similar to this:
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/8463d924-a65a-4a5a-b65a-2215adad1fb2)

**Comment by nk25719** [comment]
<img width="171" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/42283dff-abf4-47eb-a0e4-70dde90490f5">  

> A screenshot of the relocation of the capacitors.

**Comment by ForrestErickson** [comment]
Although this application notes use only one each capacitor on the input and output of the three terminal regulator, an example for component placement and trace routing can be found  on page 17 figure 27. 

https://www.ti.com/lit/ds/symlink/lm7800.pdf?ts=1717929189344&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FLM7800

Before making any changes to the component placement and routing, we should discuss what happens when two capacitors are placed in parallel for some insight.

**Comment by nk25719** [comment]
<img width="576" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/d13cbed4-ae67-416e-abc1-93786212d86d">

> Capacitors are placeds for a better high frequency, and to minimize stray capacitance.

**Comment by ForrestErickson** [comment]
Regarding, "and to minimize stray capacitance."
It is to minimize stray inductance.  Inductance is lead length.  A discussion of how to visualize magnetic field around a conductor is a rabbet hole down which we might go some time.

**Comment by nk25719** [comment]
I noteed this down. thank you for the correction.
