### ISSUE TITLE
Make R7 Into 1 Ohm. 

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#13]

**Comment by nk25719** [comment]
To get 3.3 A out of the GPIO pin#30 of the ESP32 
A resistor R7 of 1 Ohm is connected to the GPIO pin#30 3.3 V of the ESP32 

<img width="177" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/efdf7f9e-3b71-4f0a-8612-9329da7a422f">

**Comment by ForrestErickson** [comment]
Good work.
