### ISSUE TITLE
Possible Grid Problem with ESP32 Symbol

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#14]
Pins may not be on 0.050 grid.
Place the pin number text avoiding lines.

Example where the flag could not be placed.
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/179fba9b-8628-4395-bddf-f5ddbee9fd28)

**Comment by nk25719** [comment]
The ESP32 symbol was initially created on Grid 0.0050 in (0.127 mm).

As of 20240428, the ESP32 symbol has been edited and is now on Grid 0.0500 in (1.2700 mm).


<img width="759" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/294d808b-4297-490d-bf82-4b91fa5279ce">    

 >> In the screenshot of the updated ESP32 symbol, we can see the library name and file name displayed to the left of the ESP32, and the grid selection shown to the right of the ESP32.

**Comment by ForrestErickson** [comment]
Good work. 
I feel vindicated warning of the nightmare of non standard grids.
