### ISSUE TITLE
The switches and the LEDs do not have a clear function as of 20240504

### ISSUE THREAD

**Issue by nk25719** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#15]
it is better if we add a silkscreen to specify the funcion of each of the switches and the LEDs

**Comment by nk25719** [comment]
Switches were given sertain function.
Silkscreen is added to indicate these functions. 

<img width="479" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/28a32ec7-6983-4e92-8aa0-5788e689649a">

**Comment by nk25719** [comment]
Functions of the LEDs are added.
Silkscreen is added to indicate these functions.


<img width="288" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/7f19e2ad-59c0-4e3d-8cb2-002ec956c3c1">

**Comment by ForrestErickson** [comment]
Hypthetical function names added to switches and LEDs on silk screen.

Closing
