### ISSUE TITLE
Learn KiCad Features for Board Manufacture with JLCPCB

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#16]
Learn to make:
BOM (BIll of material)
PL (Parts ist)
Gerber Files
Placement FIles
And the required form to submit to JLCPCB

**Comment by nk25719** [comment]
We practiced several attemps for doing these tasks.

**Comment by nk25719** [comment]
Test after removing is:open from the filter.

**Comment by nk25719** [comment]
now with pr

**Comment by nk25719** [comment]
files: 

-  Gerbers (zipped folder) containing:
 - - .gbr
 - - .drl  
 
- CPL (export from kicad and clean excel spread sheet)
- BOM ((export from kicad and clean excel spread sheet)
