### ISSUE TITLE
Back Copper Should Have Ground Fill Too, 

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#18]
## Summary
For many reasons such as helpful to electro magnetic compatibility(EMC)  and for reduced environmental waste (Copper sulfate) the places on a PCB which do not have routing traces should have a copper fill. Connecting to ground will help a designer for compliance with the requirement for electro magnetic Compatibility.

### The Opportunity
The top copper with ground fill obvious.
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/01837ccc-d102-4bcd-9963-7e7cd6fffd49)

Turn off Top Copper and we see no ground fill on Bottom
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/70d60ea3-6745-492c-b89e-4edfcafbfbfd)

### Recommended Change
Copy the top copper fill. Then change the layer to bottom.
Put vias to connect the top and bottom ground fills.  If the routing (layout) is tight this is a requirement requiring a VERY long discussion.
We should at least start the discussion of Electro Magnetic Compatibility (Design for EMC).

**Comment by nk25719** [comment]
<img width="954" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/cb1d10fd-2e76-41f0-986b-bb729479ad10">

>Bottom copper fill is added 


**There is more than one way to doing that,** 
1- trace the top copper layer and press B to fill the copper area.
2- using the fill tool define the copper fill area larger than the coutyard, the kicad contraint rule copper to edge clearance will fix the filling zone.
3-  Select the top copper fill, copied and pasted then moved to the exact same location, and then editted the layer from top to bottum in the properties dialogue.
4- Select the top copper fill, positioned the cursor on the corner, copied and pasted it without moving so it was automatically positioned, and then editted the layer from top to bottum in the properties dialogue.

<img width="356" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/477ded23-9cc0-49bc-a634-d0b712914a26">

>Properties dialogue
