### ISSUE TITLE
Add teleportation feature, random location

### ISSUE THREAD

**Issue by nk25719** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#20]
**Is your feature request related to a problem? Please describe.**
On days when I get bored I would ike to do some sight seeing.

**Describe the solution you'd like**
When I hold the "S1-morseCodeDanger1" and the "S2-RepeatCalculation1" simultaneously for 10 seconds, I transport to a random location.

**Describe alternatives you've considered**
When I hold the "S1-morseCodeDanger1" and the "S2-RepeatCalculation1" simultaneously for 10 seconds, the device will materialize a playfull kitten.

**Additional context**
<img width="499" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/cd07bf83-45a2-4050-a95a-e9305facf158">
<img width="149" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/ed5b10ed-2786-4a31-9c8d-57ffed057660">

**Comment by ForrestErickson** [comment]
What could possibly go wrong?

**Comment by nk25719** [comment]
Photo shows that we can materialize a kitten, can we do a puppy?

**Comment by nk25719** [comment]
This issue was to test the issues and the procedure of adding features for our project, using random jokes we trained how to do that. 
cc: @ForrestErickson 

Closing..
