### ISSUE TITLE
Design an Enclosure, For Prototype

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#23]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [.._.]
Electronic assemblies are sensitive to ESD (Electro static discharge) and should be protected against ESD caused by the user.  This is a primary enclosure requirement.
 
**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
An enclosure for the bread board prototype that can be fabricated by materials at hand out of tools at hand.
An enclosure which has a visual aesthetic to convey the nature of this design. (A first prototype might deliberately look home made, Made out of obviously repurposed materials whos original finish shows the original purpose.) Or a more custom look where a new finish is applied to all parts hiding the nature and history of the material origin.
The enclosure protects the integrity of the prototype to ensure it is preserved for as long as desired.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
An enclosure not for the prototype but for the Printed Circuit Assembly.
1. An enclosure where parts are ordered from vendors using additive (3D printing) technology.
2. An enclosure where parts are ordered from vendors using subtractive (cutting, bending and fasteners) technology.
3. An enclosure using a mix of technologies. 

**Additional context**
_Add any other context or screenshots about the feature request here._
A bread board prototype which can go into a box (card board for example) may be sufficent.

**Comment by nk25719** [comment]
Dublicate of issue #24 


Closing.
