### ISSUE TITLE
Use Thermal Relief on Pads on the PCB

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#26]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

There is inadequate thermal releafe on the SMD and PTH pads on the PCB
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/1c704046-4d0f-47ab-8eda-8734bc130282)

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Set the fill properties appropriately for thermal relief.

**Describe alternatives you've considered**

**Additional context**

**Comment by nk25719** [comment]
<img width="630" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/6dcb5385-4b25-4bea-8d0a-6129d404b3bb">

>select the copper fill and edit its properties, change the pad connection from ' Relief to PTH' to 'Thermal Relief', Click 'OK' then press 'B' to repour  the copper fill. Delete redundant ground traces.


<img width="540" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/d9bb1204-6d37-4854-9954-37ac8232d571">  

>Results.
