### ISSUE TITLE
PLACE JLCPCB ORDER 

### ISSUE THREAD

**Issue by nk25719** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#27]
Update the files of the finalized PCBA for the 'esp32-6leds-2switches-1pj-circuit' and place an order on JLCPCB.

**Comment by nk25719** [comment]
Add an extra connector to the board, add an extra power jack to the board, and update the footprint and the schematic before placing the order.

**Comment by nk25719** [comment]
240709 Cleared al the schematic, 
Error and warning too 

<img width="479" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/2742bad3-4ea2-49dc-8dc2-82edb5371e97">

**Comment by ForrestErickson** [comment]
Place signal names on I2C connector and UART connector.

**Comment by nk25719** [comment]
<img width="400" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/76ad1ae4-87d6-4996-b08b-7c9d1c850165">


> PCB Editor DRC Clreared

**Comment by ForrestErickson** [comment]
##  "mixed values" is indicative of an error.
The Bulk Editor shows "mixed values" on several locations which should be fixed.

![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/47eddade-716b-4d3d-9ee0-b67e0a7faabc)

**Comment by ForrestErickson** [comment]
##   Exclude Test Points
For the Test Points we do not have a JLCPCB number. Was that on purpose?

1. If it is on purpose then exclude them from the BOM.  
2. If not on purpose then find the correct JLCPCB part number and update the schematic.


![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/2072ace7-3c1e-4c04-96fb-d00436bf0116)

**Comment by ForrestErickson** [comment]
## Exclude Mounting Holes
They are a board feature, not a part so exclude from BOM / Parts List

![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/ef814d13-cbbe-40fb-851c-34c4b9fffa08)

**Comment by ForrestErickson** [comment]
## Capacitors and Others Missing Description
Fore example C2
See below for more:
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/83c24972-9cea-44ef-bb3d-0dbeaa034a6e)

**Comment by nk25719** [comment]
<html>
<body>

R8 | 62 | Resistor_SMD:R_0603_1608Metric_Pad0.98x0.95mm_HandSolder | RTT031000FTPC103197
-- | -- | -- | --



</body>
</html>

**Comment by nk25719** [comment]
<img width="661" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/be2f374e-abd2-4bef-a597-f98ac302e863">

**Comment by ForrestErickson** [comment]
Please commit all of the files from work on 20240710.

**Comment by ForrestErickson** [comment]
## Summary For PCBWay Compatibility

To the existing fields of part numbers a new field for PCBWay Part numbers must be added.   
Do not overwrite the JLCPCB part numbers.

**Comment by nk25719** [comment]
> Please commit all of the files from work on 20240710.

The files are added.

**Comment by ForrestErickson** [comment]
@nk25719 
Please add into this issue the message we got from JLCPCB regarding can not ship to Lebanon.
Please add into this issue the notes / correspondence with PCBWay regarding the BOM and other file compatibility.

**Comment by ForrestErickson** [comment]
## JLCPCB Order Journal

I have found BOM files at: \KiCad-esp32-6leds-2switches-1pj-circuit\JLCPCB20240710

Lee started setting up a JLCPCB order for USA.
The 62 ohm resistor in our BOM was insufficent stock so I substituted for this PN: C308152

Component placement preview:
![image](https://github.com/user-attachments/assets/e4d7e2f3-3bd0-4578-a295-338a0db71b7e)


Order ready:
![image](https://github.com/user-attachments/assets/608f35bd-a968-4b1c-996d-dba7b01ea327)

As ordered:
![image](https://github.com/user-attachments/assets/414f12fa-2609-43bb-8f80-76087109b7b1)

**Comment by ForrestErickson** [comment]
---------- Original Message ----------
From: JLCPCB <noreply@jlcpcb.com>
To: forresterickson@comcast.net
Date: 07/17/2024 8:17 PM EDT
Subject: Please confirm production file of your JLCPCB order

Dear ForrestErickson,
The production file of your order completed. Your order 2999181A_Y16 is ready for manufacturing now.

To avoid production delays, please check and confirm the production file through your [order history](https://mandrillapp.com/track/click/31015052/jlcpcb.com?p=eyJzIjoiU0dYUXhXa2JoSjZRa0RURml0WmN6cmJieHVBIiwidiI6MSwicCI6IntcInVcIjozMTAxNTA1MixcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2psY3BjYi5jb21cXFwvdXNlci1jZW50ZXJcXFwvb3JkZXJzXFxcL1wiLFwiaWRcIjpcIjVjOWNjN2E2M2ViODRhNmZiMDFmOGYzM2JiOGI3YzI4XCIsXCJ1cmxfaWRzXCI6W1wiNGJhOThhMTA2YzBmYTI0NzcwZjIxNGNmNzQ0NmNhMzk0NDFiMjJjN1wiXX0ifQ) ASAP.

This is an automatically generated email – please do not reply to it. If you have any queries regarding your order please email [support@jlcpcb.com](mailto:support@jlcpcb.com). 

Sincerely,

JLCPCB Support Team

I am confirming the order. First of the PCBs.
However the PWA (printed wiring assembly) analysis shows a problem.

Zoom in on the PCB

From this preview, It looks like C7 and C9 need a larger body part.

However when I look up the part, C2895272, it is a 5x5.4 
Asking the on line support for help.

This part might also work:
VS1C470MC054000CE0
Manufacturer  Changzhou Huawei Elec
MFR.Part #  VS1C470MC054000CE0
JLCPCB Part #  C240546
Package  SMD,D5xL5.4mm
Description  47uF 16V ±20% SMD,D5xL5.4mm Aluminum Electrolytic Capacitors - SMD ROHS

We resolved the placement of the three capacitors and the polarity of D2.
I think the order is proceeding.


Lee

**Comment by nk25719** [comment]
> @nk25719 Please add into this issue the message we got from JLCPCB regarding can not ship to Lebanon. Please add into this issue the notes / correspondence with PCBWay regarding the BOM and other file compatibility.


<img width="711" alt="image" src="https://github.com/user-attachments/assets/235979d9-7f0e-4341-bfec-9703ab8e72f1">


Shipping from JLCPCB to Beirut, Lebanon is not available. 

**PCBWAY is another manufacturer and they ship to Lebanon, Issue #30 for ref.**

**Comment by ForrestErickson** [comment]
Order received in Maryville.
![image](https://github.com/user-attachments/assets/118af87b-0816-4f63-926d-66eccd509cf5)

Closing.
