### ISSUE TITLE
Assemble PCBWAY Order of 202407

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#33]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
Capture the out of box experience of receiving the PCBWAY Order of 202407 including finish assembly

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Capture of every step.

**Comment by nk25719** [comment]
### Journal of Assembly 

The shipping package
![IMG_2596_2](https://github.com/user-attachments/assets/8065ad39-61e6-498e-a1fb-9b2c694a9af0)


Inside the Shipping Package
![IMG_2597](https://github.com/user-attachments/assets/9c2c6744-c9d7-4f9b-9c6e-dd9163b574a9)


Wrapping of the PCBAs
![IMG_2598](https://github.com/user-attachments/assets/664ed05e-f383-43ab-8c20-f75267171239)

Unwrapping of Assemblies
![IMG_2599](https://github.com/user-attachments/assets/0e6b92e0-7186-4ba5-a673-d9ae17420c56)

Unpacking Assemblies
![IMG_2600](https://github.com/user-attachments/assets/5ddfafef-a57f-4ecf-a023-a8a18d768956)

Closer Look, Top View 
![IMG_2601](https://github.com/user-attachments/assets/fdf87abc-e23c-49e7-827b-71a4b199129f)

Closer Look, Bottom View 
![IMG_2602](https://github.com/user-attachments/assets/15819673-f2de-4892-ad10-cb18ab7a8c62)

Checking Assemply, Wrong pin spacing on DIP for ESP32
![IMG_2603](https://github.com/user-attachments/assets/e2bd5cd8-857b-4f90-89ca-3d3b84ad2abe)

## Containment of Pin Spacing 

![IMG_2606](https://github.com/user-attachments/assets/0efda93b-65d5-41d4-aa5e-a3e28b9a55df)

connected the ESP32 and Assembled the LEDs

**Comment by nk25719** [comment]
**Factory Test with Firmware**

To verify the hardware assembly, several factory test codes were used:

- **Marching One and Marching Zero test codes** were used to test the LEDs.
- Switch functionality was successfully tested.
- The power jack was tested and confirmed to be working.
- The ESP32 was mounted on the board (the dimensions were not compatible, so the ESP32 legs were modified to fit).
- The connectors for the LCD and DFPlayer were tested, with positive results.

**Conclusion**: The assembly is properly designed, and the PCB functions as expected.

<img width="362" alt="Screenshot 2024-10-12 092518" src="https://github.com/user-attachments/assets/06689ddf-06e5-4ac7-a9e4-59c3e15c6973">



Closing..
