### ISSUE TITLE
Enhance the Factory Test Firmware, LED Test.

### ISSUE THREAD

**Issue by nk25719** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#36]
**Is your feature request related to a problem? Please describe.**
_The current Test fails to detect shorts  between LEDs_
_Opperate every LED independantly of every other LED_

**Describe the solution you'd like**
_Adding a Marching 1 and a marching 0_ 

**Describe alternatives you've considered**

**Additional context**

**Comment by ForrestErickson** [comment]
I decided to ask ChatGPT for some coding ideas.  It returned this which I have not tried:

https://chatgpt.com/share/8afc3085-eb42-4212-ace3-92c104a99e49

**Comment by nk25719** [comment]
https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/tree/main/FIRMWARE/marchingOneTest

https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/tree/main/FIRMWARE/marchingZeroTest

cc: @ForrestErickson
