### ISSUE TITLE
The Power Jack (AKA Barrel Jack) Needs To Be Near / Overhang Board Edge.

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#4]
#  Summary
The layout of 20240421 has poorly placed Power Jack. 
The PCB will interfer with fingers 
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/8801fc8a-3204-4cac-9532-9dec03a173d0)

## Suggestion(s)
The barrel jack must overhang the edge of the PCB.  So that it might be flush with an enclosure.
In which Direction / edge of the PCB should the power jack be located?

**Comment by nk25719** [comment]
I received error messages when I let the barrel jack overlay the courtyard, and also the silkscreen was outside the Front silkscreen layer. 
After I received these error messages I placed the BJ at the edge of the board but not overlaying it. 

<img width="380" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/c6de911a-136f-4efc-b476-0b4354d8ff92">

**Comment by ForrestErickson** [comment]
The enclosure designer (Either you or someone else in a "company") must provide the requirement for how much the power jack should overhang the edge of the PCB.  

 This overhang must be equal to the enclosure thickness plus the uncertainty on the edge of the PCB (when it is routed or cut by JCLPCB) and possibly a small extra clearance.

Enclosure thickness = ______
PCB edge tolerance = ______
Extra clearance = _______


Add these up for the overhang.

**Comment by nk25719** [comment]
Assume enclosure thickness of 2 mm, 
JLCPCB tolerance is +- 0.1 mm

**Comment by ForrestErickson** [comment]
Regarding "Clearance: refers to the distance between the enclosure and the PCB."
Yes it does. I also called the same distance the overhang of the connector. 

## Example of Flush Mounted Connectors
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/8d97f746-80e3-4314-bbb5-a4c65004663d)

**Comment by ForrestErickson** [comment]
We do not have an enclosure which drives any other requirements and so this has been fixed (To the extent possible at the present. Had we an enclosure to which we had to design we would need to place so that the power barrel jack surface was correct for the enclosure.)

Closing.
