### ISSUE TITLE
Notes on Assembly, LED Pattern During Reset

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#47]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

This issue is simply to capture the typical behavior observed on a KiCad-esp32-6leds-2switches-1pj-circuit assembly during the ESP32 reset condition.

## Typical Reset LED Behavior
![image](https://github.com/user-attachments/assets/a5d649a8-a837-41b5-8df6-f01878fac883)
Only the power LED near J1 and the D8 LED are illuminated. D8 is not full brightness

## Conclusion
If an assembly does not have this behavior suspect a hardware problem.

**Comment by nk25719** [comment]
<img width="511" alt="image" src="https://github.com/user-attachments/assets/af8c0fd1-3ddf-4ff1-8a94-f8307e5bd22e">

> LED 8 is connected to D5

<img width="701" alt="image" src="https://github.com/user-attachments/assets/a305e4c7-62f5-4106-b44d-4c9365b88e3c">

> Captured pin D5 functionalities

**Comment by ForrestErickson** [comment]
Lee found a schematic for by search on "schematic diagram for esp32 dev kit1 V1"
See: 
https://embedded-systems-design.github.io/overview-of-the-esp32-devkit-doit-v1/
Look for schematic at this URL:
https://embedded-systems-design.github.io/overview-of-the-esp32-devkit-doit-v1/SchematicsforESP32.pdf
Detail showing the 10K pull up on D5
![image](https://github.com/user-attachments/assets/99035935-3481-4bcb-b9e5-031d00c94fc5)

### Conclusions
The soft illumination of the Diode D8 on the PMD when the system is in reset is behavior we can expect.
There is no dangerous (no latent) failures of any hardware likely.

Closing this issues as explained.
This information might be incorporated into a Factory Test document if one is ever written.
