### ISSUE TITLE
No Copper in Antenna Radiation Pattern

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#5]
# Summary
There must be no conductor in the antenna radiation pattern.

The 20240421 has some copper which must be removed.
Here is the bottom layer:
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/ddc9bb78-4bd8-4b52-be7b-86cb8e35be28)

**Comment by nk25719** [comment]
I extended the keepout zone area around the antenna. 
(No more copper in the front and in the back layers)

<img width="955" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/4e0adf11-75ee-45d9-a9c0-9770bc7bbc07">

**Comment by ForrestErickson** [comment]
This has been fixed. 
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/696457c4-2b7a-407c-9df0-a39fccdfd40a)

Closing.
