### ISSUE TITLE
ESP32 ID for every board 

### ISSUE THREAD

**Issue by nk25719** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#52]
**Is your feature request related to a problem? Please describe.**
when we connect more than one esp32 at once we need to have an ID identification to know which module we are connecting to

**Describe the solution you'd like**
_Identify the unique MAC address for each ESP32 module_

**Describe alternatives you've considered**
__SOLUTION:_ upload a code with a unique ID for each module_ 
code example:
```
#define DEVICE_ID "ESP32-1"  // Change this for each device

void setup() {
  Serial.begin(115200);
  Serial.print("Device ID: ");
  Serial.println(DEVICE_ID);
}

void loop() {
  // Do nothing
}
```

**Additional context**
_This way, we can identify each ESP32 by its custom DEVICE_ID and, be able to distinguish between multiple ESP32 devices when connected._

**Comment by nk25719** [comment]
When connecting different ESP32 modules and uploading the firmware to display the MAC address, each of the ESP32 modules displayed the same MAC address. 

# CODE

```
#include "WiFi.h"

void setup() {
  Serial.begin(115200);
  // Get the MAC address
  Serial.print("ESP32 MAC Address: ");
  Serial.println(WiFi.macAddress());
}

void loop() {
  // Do nothing
}
```

# OUTPUT:

<img width="555" alt="image" src="https://github.com/user-attachments/assets/fd395048-a389-4cb5-8531-fd3d643a70b4">

cc: @ForrestErickson

**Comment by nk25719** [comment]
Similar output after using the code
WiFiAccessPointWithMAC.ino
on : https://github.com/ForrestErickson/WiFiAccessPointWithMAC/blob/main/WiFiAccessPointWithMAC.ino 

<img width="510" alt="image" src="https://github.com/user-attachments/assets/48a5bda5-353c-4559-91b8-c8aa705a16b8">

>ESP32 module A

<img width="536" alt="image" src="https://github.com/user-attachments/assets/a7100449-60dd-4fb0-89b3-bf0ff4116abb">

>ESP32 module B

**Comment by nk25719** [comment]
trying: 



```

#include <WiFi.h>
#include <esp_wifi.h>

void readMacAddress(){
  uint8_t baseMac[6];
  esp_err_t ret = esp_wifi_get_mac(WIFI_IF_STA, baseMac);
  if (ret == ESP_OK) {
    Serial.printf("%02x:%02x:%02x:%02x:%02x:%02x\n",
                  baseMac[0], baseMac[1], baseMac[2],
                  baseMac[3], baseMac[4], baseMac[5]);
  } else {
    Serial.println("Failed to read MAC address");
  }
}

void setup(){
  Serial.begin(115200);

  WiFi.mode(WIFI_STA);
  WiFi.STA.begin();

  Serial.print("[DEFAULT] ESP32 Board MAC Address: ");
  readMacAddress();
}
 
void loop(){

}
```

## Result 

<img width="565" alt="image" src="https://github.com/user-attachments/assets/89c49ff2-7d15-43b9-8c57-5364db773e28">

>Mac Address: cc:db:a7:30:09:54

**Comment by ForrestErickson** [comment]
Lee copied the code directly above.

It would not compile till line was commented out.
![image](https://github.com/user-attachments/assets/13b3d848-b3f9-422f-bced-a69f701f5a8b)

It then compiled and ran and returned the exact same MAC address as returned by the program Lee wrote.
![image](https://github.com/user-attachments/assets/56cd7c7c-fab7-476f-91a6-3e5dc0b2d140)

This code returns the MAC address (which should be unique) of the ESP kit.

**Comment by ForrestErickson** [comment]
Closing because this method found an ESP21 ID.

**Comment by ForrestErickson** [comment]
@nk25719 
I have closed this because as written this issue requirement was "when we connect more than one esp32 at once we need to have an ID identification "

It still remains for you to use this MAC address in the KRAKE code and in the PMD code.

I will warn you the code you developed has the address in a format which may be very difficult use.  It is not in one variable either as C character array or a C++ String.

As you try to put this into KRAKE and PMD I can help.

Lee

**Comment by nk25719** [comment]
ok, I understand,

I am surprised and not able to find the reason why one code pulled the Mac
Address and the second did not,
both worked and pulled the mac address of your ESP3232 modules, right?

Nagham.
