### ISSUE TITLE
Add to Pin Signal Names for ESP32 Kit FootPrint

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#6]
# Summary
It helps troubleshooting if the pin names are identified on the PCB bottom silk screen

## Partial Example
![image](https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/5836181/ec281ce4-7e48-41f9-9974-2ea35cc07da1)

**Comment by nk25719** [comment]
<img width="192" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/59f4440c-9c10-40b4-8785-f85f2402b19c">

This is the 3D view of the result. 
Thank you for the tip.

**Comment by ForrestErickson** [comment]
Very good.
