### ISSUE TITLE
Warning upon Branch Renaming  

### ISSUE THREAD

**Issue by nk25719** [nk25719/KiCad-esp32-6leds-2switches-1pj-circuit#7]
We renamed the branch from Net-Classes to PCB-Barrel-Jack-ESP32-PIN-Names 

## This is the message we received from github upon renaming the branch
>> and we are capturing it in this issue incase we need it in the future

 
Renaming this branch will not update your members' local environments.

Your members will have to manually update their local environments. We'll let them know when they visit the repository, or you can share the following commands.

  git branch -m PCB-Barrel-Jack-ESP32-PIN-Names PCB-Barrel-Jack-ESP32-PIN-Names
  git fetch origin
  git branch -u origin/PCB-Barrel-Jack-ESP32-PIN-Names PCB-Barrel-Jack-ESP32-PIN-Names
  git remote set-head origin -a
  

<img width="386" alt="image" src="https://github.com/nk25719/KiCad-esp32-6leds-2switches-1pj-circuit/assets/133608369/1b72c7a9-e88e-4f7c-b435-76903170f3b6">

**Comment by ForrestErickson** [comment]
@nk25719 
Has this created any problems?
Is there something to investigate further?

If not this could be closed.

**Comment by nk25719** [comment]
This has not created any problems and nothing to invastigate here. closing issue.
